### ISSUE TITLE
mono channel crashes

### ISSUE THREAD

**Issue by greyboxaudio** [greyboxaudio/SG-323#17]
probably line 643

**Comment by ravettel** [comment]
outputBuffer.setSample(1, i, rightOutputSample);
monoBuffer.addFrom(0, 0, buffer, 1, 0, bufferSize);

**Comment by ravettel** [comment]
fixed in dev branch. still evaluating the most elegant solution to handle mono instances.

**Comment by greyboxaudio** [comment]
fixed in latest release
